function whatsappUrl(m){return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(m)}`;}
function artText(a,key){const frKey=key+'Fr'; return currentLang()==='fr' && a[frKey] ? a[frKey] : (a[key]||'');}
function render(){
  const id=parseInt(new URLSearchParams(location.search).get("id"),10), a=ARTWORKS[id], c=document.getElementById("artworkDetail");
  if(!a){c.innerHTML=`<section class="missing-artwork"><p class="eyebrow">${tr('artworkLabel')}</p><h1>${tr('artworkNotFound')}</h1><a class="button button-gold" href="index.html#gallery">${tr('returnGallery')}</a></section>`;return;}
  document.title=`${artText(a,'title')} | GLoiART`;
  const m=`Hello GLoiART, I would like to enquire about "${a.title}".`;
  const prints=(a.printImages||[a.image]).map((x,i)=>`<figure><img src="${x}" alt="${artText(a,'title')} ${tr('printExample')} ${i+1}"><figcaption>${(a.printImageCaptions||[])[i]||tr('printExample')}</figcaption></figure>`).join("");
  c.innerHTML=`<section class="art-detail-hero"><a class="back-link" href="index.html#gallery">${tr('backGallery')}</a><div class="detail-main-grid"><div class="detail-main-image"><img src="${a.image}" alt="${artText(a,'title')}"></div><div class="detail-intro"><p class="eyebrow">${tr('artworkLabel')} ${String(id+1).padStart(2,"0")}</p><h1>${artText(a,'title')}</h1><p class="detail-lead">${artText(a,'description')}</p><div class="availability-large ${a.original?"":"sold"}">${artText(a,'availability')}</div><div class="spec-grid"><div class="spec"><span>${tr('size')}</span><strong>${a.size||tr('addArtworkSize')}</strong></div><div class="spec"><span>${tr('medium')}</span><strong>${a.medium||tr('addMedium')}</strong></div><div class="spec"><span>${tr('original')}</span><strong>${artText(a,'availability')}</strong></div><div class="spec"><span>${tr('prints')}</span><strong>${a.printAvailability||tr('contactAvailability')}</strong></div></div><a class="button button-gold" href="${whatsappUrl(m)}" target="_blank">${tr('buyArtwork')}</a></div></div></section><section class="detail-section story-section"><div class="detail-section-heading"><p class="eyebrow">${tr('theStory')}</p><h2>${tr('aboutArtwork')}</h2></div><p class="story-text">${artText(a,'story')}</p></section><section class="detail-section process-section"><div class="detail-section-heading"><p class="eyebrow">${tr('behindArtwork')}</p><h2>${tr('watchProcess')}</h2></div><div class="process-large"><video controls preload="metadata" poster="${a.image}"><source src="${a.processVideo}" type="video/mp4">${tr('browserVideo')}</video></div></section><section class="detail-section print-section"><div class="detail-section-heading"><p class="eyebrow">${tr('space')}</p><h2>${tr('printOptions')}</h2><p>${artText(a,'print')}</p></div><div class="print-gallery">${prints}</div><div class="print-cta"><div><strong>${tr('interestedPrint')}</strong><p>${tr('askPricing')}</p></div><a class="button button-gold" href="${whatsappUrl(m)}" target="_blank">${tr('chatWhatsApp')}</a></div></section><section class="detail-bottom"><a href="index.html#gallery">${tr('continueBrowsing')}</a></section>`;
  const social={socialTikTok:TIKTOK_URL,socialFacebook:FACEBOOK_URL,socialYouTube:YOUTUBE_URL,socialInstagram:INSTAGRAM_URL,socialWhatsApp:whatsappUrl("Hello GLoiART, I would like to contact you.")};
  Object.entries(social).forEach(([id,url])=>{const el=document.getElementById(id);if(el&&url)el.href=url;});
  const y=document.getElementById("year"); if(y)y.textContent=new Date().getFullYear();
}
document.addEventListener("DOMContentLoaded",()=>{ if(typeof applyLanguage==='function') applyLanguage(); render(); });
